elib/books/urls.py
from django.urls import path

from .views import search_books, detailed_view

app_name = 'books'

urlpatterns = [
    path('', search_books, name='search_books'),
    path('<int:book_id>/', detailed_view, name='book_detail'),
]

elib/elib/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('favourites/', include('favourites.urls', namespace='favourites')),
    path('login/', include('login.urls', namespace='login')),
    path('registration/', include('register.urls', namespace='registration')),
    path('books/', include('books.urls', namespace='books')),
    path('', include('homepage.urls', namespace='homepage')),
]

elib/favourites/urls.py
from django.urls import path
from .views import favourites_view, add_favorite_book

app_name = 'favourites'

urlpatterns = [
    path('', favourites_view, name='favourites'),
    path('add/<int:book_id>/', add_favorite_book, name='add_favorite_book'),
]

elib/homepage/urls.py
from django.urls import path
from .views import homepage

app_name = 'homepage'

urlpatterns = [
    path('', homepage, name='home'),
]

elib/login/urls.py
from django.urls import path
from .views import login_user


app_name = 'login'


urlpatterns = [
    path('', login_user, name='login'),
]

elib/register/urls.py
from django.urls import path
from .views import register_user

app_name = 'registration'

urlpatterns = [
    path('', register_user, name='register'),
]

elib/books/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    description = models.TextField(max_length=128)
    full_description = models.TextField(max_length=512)
    published_date = models.DateField()
    file = models.FileField(upload_to='books/')
    image = models.FileField(upload_to='images/')

    def __str__(self):
        return self.title

elib/favourites/models.py
from books.models import Book
from django.contrib.auth.models import User
from django.db import models


class FavoriteBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'book')

    def __str__(self):
        return f"{self.user.username} - {self.book.title}"

elib/books/views.py
import typesense

from django.shortcuts import render, get_object_or_404

from .models import Book

client = typesense.Client({
    'nodes': [{
        'host': 'localhost',
        'port': '8108',
        'protocol': 'http'
    }],
    'api_key': 'xyz',
})


def search_books(request):
    title = request.GET.get('title')
    try:
        response = client.collections['books'].documents.search({
            'q': title,
            'query_by': 'title',
            'sort_by': 'sorting_id:asc'
        })

        book_ids = [hit['document']['sorting_id'] for hit in response['hits']]

        books = Book.objects.filter(id__in=book_ids)

        context = {'books': books}
        return render(request, 'books/books.html', context)

    except Exception as e:
        print(f"Ошибка поиска: {e}")
        return render(request, 'books/books.html', {'error': 'Произошла ошибка при поиске.'})



def detailed_view(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    return render(request, 'books/book_detail.html', {'book': book})

elib/favourites/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import FavoriteBook, Book


@login_required
def add_favorite_book(request, book_id):
    try:
        book = Book.objects.get(id=book_id)
        created = FavoriteBook.objects.get_or_create(user=request.user,
                                                     book=book)

        if created:
            messages.success(request,
                             f"Книга '{book.title}' добавлена в ваши любимые!")
        else:
            messages.warning(request,
                             f"Книга '{book.title}' уже в списке любимых.")

    except Book.DoesNotExist:
        messages.error(request, "Книга не найдена.")

    return redirect('favourites:favourites')


def favourites_view(request):
    favorite_books = FavoriteBook.objects.filter(user=request.user).select_related('book')
    latest_book = favorite_books.last()
    other_books = favorite_books.exclude(id=latest_book.id) if latest_book else []

    return render(request, 'favourites/favourites.html', {
        'latest_book': latest_book,
        'other_books': other_books,
    })

elib/homepage/views.py
from django.shortcuts import render
from books.models import Book


def homepage(request):
    books_rev = Book.objects.all().order_by('-id')
    context = {'books': books_rev}
    return render(request, 'homepage/homepage.html', context)

elib/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages


def login_user(request):
    """
    Обрабатывает вход пользователя.

    Если запрос POST, проверяет учетные данные пользователя.
    При успешной аутентификации выполняет вход в аккаунт.
    В случае ошибки отображает сообщение.
    """
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('homepage:home')
        else:
            messages.error(request, 'Неверное имя пользователя или пароль.')

    return render(request, 'login/login.html')

elib/register/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages


def register_user(request):
    """
    Функция для регистрации нового пользователя.

    Если метод запроса POST, обрабатывает данные формы регистрации.
    Проверяет совпадение паролей и наличие пользователя с таким же именем или email.
    Если проверки пройдены, создаёт нового пользователя и перенаправляет на страницу входа.
    """
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            if User.objects.filter(username=username).exists():
                messages.error(request, 'Пользователь с таким именем уже существует.')
            elif User.objects.filter(email=email).exists():
                messages.error(request, 'Пользователь с таким email уже существует.')
            else:
                user = User.objects.create_user(username=username, email=email, password=password)
                user.save()
                return redirect('login:login')
        else:
            messages.error(request, 'Пароли не совпадают.')

    return render(request, 'register/register.html')

elib/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head><script src="{% static 'js/color-modes.js' %}"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="generator" content="Hugo 0.122.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="{% static 'images/home.ico' %}" type="image/x-icon">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/carousel/">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" integrity="sha384-tViUnnbYAV00FLIhhi3v/dWt3Jxw4gZQcNoSCxCIFNJVCx7/D55/wXsrNIRANwdD" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
      html, body {
      height: 100%;
      margin: 0;
      display: flex;
      flex-direction: column;
      }

      /* Контент займёт оставшееся место */
      .content {
        flex: 1;
      }

      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
          --bd-gray-bg: #6c757d;
          --bd-gray-rgb: 108, 117, 125;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-gray-bg);
          --bs-btn-border-color: var(--bd-gray-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #5a6268;
          --bs-btn-hover-border-color: #5a6268;
          --bs-btn-focus-shadow-rgb: var(--bd-gray-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #545b62;
          --bs-btn-active-border-color: #545b62;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'carousel.css' %}" rel="stylesheet">
  </head>
  <body>
    {% include "includes/theme_switch.html" %}
    {% include "includes/header.html" %}
    <main>
      {% block content %}{% endblock %}
    </main>
    {% include "includes/footer.html" %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/epubjs@latest/dist/epub.js"></script>
    <script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

elib/templates/books/book_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  E-lib
{% endblock %}

{% block content %}
<div class="container col-xxl-8 px-4 py-5">
  <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
    <!-- Блок с описанием книги -->
    <div class="col-lg-6">
      <h1 class="display-6 fw-bold lh-1">{{ book.title }}</h1>
      <h2 class="text-muted">{{ book.author }}</h2>
      <p class="py-3">{{ book.description }}</p>
      <h3 class="text-secondary">{{ book.published_date }}</h3>
      <h3 class="pt-5">{{ book.full_description }}</h3>
      <div class="btn-group mt-4">
        <a href="{% url 'books:book_detail' book.id %}">
          <button type="button" class="btn btn-secondary btn-sm">Download</button>
        </a>
        {% if user.is_authenticated %}
          <a href="{% url 'favourites:add_favorite_book' book.id %}">
            <button type="button" class="btn btn-outline-secondary btn-sm">Add to Favourites</button>
          </a>
        {% else %}
          <a href="{% url 'login:login' %}">
            <button type="button" class="btn btn-outline-secondary btn-sm">Add to Favourites</button>
          </a>
        {% endif %}
      </div>
    </div>

    <!-- Блок с изображением -->
    <div class="col-10 col-sm-8 col-lg-6">
      <img src="{% static book.image %}" class="img-fluid" alt="{{ book.title }}">
    </div>
  </div>
</div>

{% endblock %}

elib/templates/books/books.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  E-lib
{% endblock %}

{% block content %}
<div class="container py-5">
    {% for book in books %}
    <div class="container">
      <h1 class="py-3">{{ book.title }}</h1>
      <h2 class="py-3">{{ book.author }}</h1>
      <img src="{% static book.image %}" class="bd-placeholder-img card-img-top img-fluid h-50 w-25" width="100%" height="100" alt="{{ book.title }}">
      <p class="py-2">{{ book.description }}</p>
      <h3 class="py-2">{{ book.published_date }}</h3>
      <div class="btn-group">
        <a href="{% url 'books:book_detail' book.id %}">
          <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
        </a>
        {% if user.is_authenticated %}
          <a href="{% url 'favourites:add_favorite_book' book.id %}">
              <button type="button" class="btn btn-sm btn-outline-secondary">Add to Favourites</button>
          </a>
        {% else %}
          <a href="{% url 'login:login' %}">
              <button type="button" class="btn btn-sm btn-outline-secondary">Add to Favourites</button>
          </a>
        {% endif %}
      </div>
    </div>

{% endfor %}</div>

{% endblock %}

elib/templates/favourites/favourites.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Favourites
{% endblock %}

{% block content %}
  <div class="container py-4">
    <h1 class="display-5 fw-bold text-start py-4">Ваши любимые книги</h1>

    <!-- Блок с последней книгой -->
    <div class="p-5 mb-4 bg-body-tertiary rounded-3">
      <div class="container-fluid py-5">
        {% if latest_book %}
          <h1 class="display-5 fw-bold">{{ latest_book.book.title }}</h1>
          <p class="col-md-8 fs-4">Автор: {{ latest_book.book.author }}</p>
          <p>Описание: {{ latest_book.book.description }}</p>
        {% else %}
          <p>У вас пока нет избранных книг.</p>
        {% endif %}
      </div>
    </div>

    <!-- Блок с остальными книгами -->
    <div class="row align-items-md-stretch">
      {% for favorite in other_books %}
        <div class="col-md-6">
          <div class="h-100 p-5 bg-body-tertiary border rounded-3">
            <h2>{{ favorite.book.title }}</h2>
            <p>Автор: {{ favorite.book.author }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

elib/templates/homepage/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  E-lib
{% endblock %}

{% block content %}
  <!--Carousel-->
  <div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2" class=""></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3" class="active" aria-current="true"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active bg-dark">
        <div class="container">
            <div class="carousel-caption text-start text-light">
                <h1>Worldwide.</h1>
                <p>Some representative placeholder content for the third slide of this carousel.</p>
                <p><a class="btn btn-lg btn-secondary" href="#">Learn more</a></p>
            </div>
        </div>
        <img src="{% static 'images/pexels-nietjuh-697662.jpg' %}" class="img-fluid" alt="">
      </div>
      <div class="carousel-item bg-dark">
        <img src="{% static 'images/pexels-polina-zimmerman-3747468.jpg' %}" class="d-block" alt="Description of image">
        <div class="container">
            <div class="carousel-caption text-end text-dark">
                <h1>Find any book you want.</h1>
                <p>Some representative placeholder content for the second slide of the carousel.</p>
                <p><a class="btn btn-lg btn-secondary" href="#">Learn more</a></p>
            </div>
        </div>
      </div>
      <div class="carousel-item bg-dark">
        <div class="container">
            <div class="carousel-caption text-start text-light">
                <h1>Online library.</h1>
                <p>Some representative placeholder content for the third slide of this carousel.</p>
                <p><a class="btn btn-lg btn-secondary" href="#">Browse gallery</a></p>
            </div>
        </div>
        <img src="{% static 'images/pexels-technobulka-2908984.jpg' %}" class="img-fluid float-end" alt="">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Album -->
  <h1 class="text-center">New Books</h1>
  <div class="album py-5 bg-body-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">
        {% for book in books %}
          <div class="col">
            <div class="card shadow-sm">
              <img src="{% static book.image %}" class="bd-placeholder-img card-img-top img-fluid h-50" width="100%" height="225" alt="{{ book.title }}">
              <div class="card-body">
                <h5 class="card-title">{{ book.title }}</h5>
                <p class="card-text">{{ book.description|truncatewords:7 }}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a href="{% url 'books:book_detail' book.id %}">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    </a>
                    {% if user.is_authenticated %}
                      <a href="{% url 'favourites:add_favorite_book' book.id %}">
                          <button type="button" class="btn btn-sm btn-outline-secondary">Add to Favourites</button>
                      </a>
                    {% else %}
                      <a href="{% url 'login:login' %}">
                          <button type="button" class="btn btn-sm btn-outline-secondary">Add to Favourites</button>
                      </a>
                    {% endif %}
                  </div>
                  <small class="text-body-secondary">{{ book.published_date }}</small>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock %}

elib/templates/includes/footer.html
{% load static %}
<footer class="footer footerf mt-auto py-3 bg-danger">
  <div class="container d-flex justify-content-between align-items-center">
    <span class="text-body-secondary">
      <a class="navbar-brand" href="{% url 'homepage:home' %}">
        <img src="{% static 'images/home.png' %}" alt="">
      </a>
    </span>
    <span class="text-white">
      &copy; 2024 Your Company. All rights reserved.
    </span>
  </div>
</footer>

elib/templates/includes/header.html
{% load static %}
<header data-bs-theme="dark">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-danger">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'homepage:home' %}"><img src="{% static 'images/home.png' %}" alt=""></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
              <a class="nav-link disabled text-light" aria-disabled="true" href="{% url 'homepage:home' %}"><strong>E-Library</strong></a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'favourites:favourites' %}" class="nav-link text-dark"><strong>Favourites</strong></a>
            </li>
          {% else %}
            <li class="nav-item">
              <a href="{% url 'login:login' %}" class="nav-link text-dark"><strong>Login</strong></a>
            </li>
          {% endif %}

          </ul>
          <form class="d-flex" role="search" method="GET" action="{% url 'books:search_books' %}">
            <input class="form-control me-2" style="width: 220px;" name="title" type="search" placeholder="Введите название книги " aria-label="Search" required>
            <button class="btn btn-secondary" type="submit">Search</button>
          </form>
      </div>
    </div>
  </nav>
</header>

elib/templates/includes/theme_switch.html
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="check2" viewBox="0 0 16 16">
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  </symbol>
  <symbol id="circle-half" viewBox="0 0 16 16">
    <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
  </symbol>
  <symbol id="moon-stars-fill" viewBox="0 0 16 16">
    <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
    <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
  </symbol>
  <symbol id="sun-fill" viewBox="0 0 16 16">
    <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
  </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
  <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
          id="bd-theme"
          type="button"
          aria-expanded="false"
          data-bs-toggle="dropdown"
          aria-label="Toggle theme (auto)">
    <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
    <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
  </button>
  <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
        <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
        Light
        <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
      </button>
    </li>
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
        <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
        Dark
        <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
      </button>
    </li>
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
        <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
        Auto
        <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
      </button>
    </li>
  </ul>
</div>

elib/templates/login/login.html
{% extends 'base.html' %}

{% block title %}Sign in{% endblock %}

{% block content %}
  <div class="container vh-100 d-flex justify-content-center align-items-center">
    <div class="row w-100">
      <div class="col-md-6 mx-auto">
          <h2 class="text-center mb-4">Login</h2>

          {% if messages %}
            {% for message in messages %}
              <div class="text-center text-danger alert-{{ message.tags }} mt-3">{{ message }}</div>
            {% endfor %}
          {% endif %}

          <form method="POST">
              {% csrf_token %}
              <div class="mb-4">
                  <label for="username" class="form-label">Username</label>
                  <div class="input-group">
                      <span class="input-group-text">
                          <i class="bi bi-person"></i>
                      </span>
                      <input type="text" class="form-control form-control-lg" id="username" name="username" required>
                  </div>
              </div>
              <div class="mb-4">
                  <label for="password" class="form-label">Password</label>
                  <div class="input-group">
                      <span class="input-group-text">
                          <i class="bi bi-lock"></i>
                      </span>
                      <input type="password" class="form-control form-control-lg" id="password" name="password" required>
                  </div>
              </div>
              <button type="submit" class="btn btn-secondary btn-lg w-100">Authorize</button>
              <div class="text-center mt-3">
                  <a href="{% url 'registration:register' %}" class="text-center">Create an account</a>
              </div>
          </form>
      </div>
    </div>
  </div>
{% endblock %}